### ISSUE TITLE
Including 3rd party libraries

### ISSUE THREAD

**Issue by Marcdup1** [Ks89/angular-webpack-skeleton#33]
Hello,

I want to include this library: https://github.com/simonbengtsson/jsPDF-AutoTable.
How can I include it in the project?

Thank you for your help.

**Comment by Ks89** [comment]
I never used this library. 
Including the original library https://github.com/MrRio/jsPDF it is working very well, without difficulties.

With AutoTable plugin I found some problems.
Finally, I found a solution (very bad, I don't like it), so I created a branch for this: https://github.com/Ks89/angular-webpack-skeleton/tree/jsPDF-AutoTable-example

You should find a way to fix the TODO inside "home.component.ts".

Compare that branch with master to understand what I've done.

If you are happy, feel free to close this issue, otherwise, please give me at least a week to investigate, because I'm quite busy next days.

**Comment by Marcdup1** [comment]
I will take a look at that ```TS2339 error```. If I manage I will let you know.

Thank you so much for your help.

**Comment by Ks89** [comment]
I found a solution, it's not necessary to include `@types/jspdf`.

Check this commit: https://github.com/Ks89/angular-webpack-skeleton/commit/0a949d222d87a02d768699e11ffc73373fb704bb

Good to know :)

Can you confirm that now everything is ok and close this issue?

Thanks

**Comment by Marcdup1** [comment]
@Ks89 Thank you so much. It is working.
