### ISSUE TITLE
How to update from beta10 to beta11

### ISSUE THREAD

**Issue by ltoshev** [Ks89/angular-webpack-skeleton#63]
Hi

the current version of master says beta11. How to update from beta10 to beta 11. What are the changes?

I need to update because I need the latest dependencies, so I can include some new components in my proj.

But I see quite a big changes, when I started to merge the new stuff. Especially in the webpack.config.js webpack.common.js and webpack.dev.js

First I tried just to update the packages.json, but then the build started failing, with some missing AutoDll plugin. 

How do you suggest to upgrade?

**Comment by ltoshev** [comment]
Why is this thing removed:

new DefinePlugin({'webpack': {'ENV': JSON.stringify(METADATA.env),

I need that one, since I wrote some other config data into it and I use it in code like so: webpack.API_PATH for example.

**Comment by ltoshev** [comment]
It is completely impossible to upgrade, this is very sad. Everything breaks.

**Comment by Ks89** [comment]
Hi. Its not a big change, it's completely rewritten.
This is not because I like to add breaking changes but because angular 5 changed everything. 

The problem is that the actual compiler is different and we cannot do anything about that. 

I talked with other developers and we discovered that most of plugins and loaders are deprecated or broken. 

Shlomiassaf, the author of ngc-webpack is the only guy that decided to continue to work on his plugin. He decided to rewrite it using NG tools by Google (plugin also used internally by angular-cli). This is not a random choice, but because the effort to support angular 5 from scratch is really huge, so he decided to use Google plugin well supported, stable and with many optimization. He wrapped this plugin that loads ts and other stuff, with ngc webpack to provide simpler api (this is why I removed many dependencies). 

This has a big advantage: migrate to angular-cli will be simpler. However, there are many breaking changes. 

The actual version on master isn't released (also there are some small bugs). At the moment is experimental. Readme is not updated and there are other things to fix. 

Angularclass and other famous starter are exactly like my skeleton, but without bootstrap and other things. 
As you can see most of them are abandoned. I decided to align my project to angularclass adding my other favorite plugins and bootstrap loader. 

Before angular 6, I'll create a new starter based on angular-cli to experiment stuff and to add bootstrap and so on. 
Since, I'll eject angular-cli config, everything learnt today will be useful next. So beta 11 will be an intermediate release before an official migration to angular cli. 

Today angular cli is very good and well supported by Google. During Christmas holidays,  I'll start to experiment something creating a new repository (something like angular-cli-skeleton). 

If you'll check Angularclass you'll see the same problems to migrate the project. 

If you need more info, I can add links to some issues in other repositories.

**Comment by Ks89** [comment]
Ps you can still expose things from webpack using Define Plugin in webpack.common in the same way. If you need an example I can update the skeleton this evening (central European time)

**Comment by Ks89** [comment]
Ps2 I migrated an enterprise application for my company using the skeleton on Master branch with other sophisticated customizations and its working very well. So I'm not saying that beta 11 isn't working but it still not ready to release it as official beta, because Readme is not updated and so on.

**Comment by ltoshev** [comment]
What I did is I downloaded master, and tried to merge with what I have. I have exposed through DefinePlugin() some settings based on dev machine name. Like URLs and etc. 

The problem I got was it did not compile and gave me strange errors when I tried to build dev.

I can try to do it again. It is very frustrating how they fuck up things from Angular 5.0.0.beta7 to 5.0.2 this is  really annoying. We are rewriting from 1.5 to 5.0. We cannot afford to rewrite every time... But this is not your fault. We may need to consider something else to use, that is more stable.

It would be great if you consider adding ngx-translate to skeleton, angular-material, ngx-cookie, those are like basic stuff for an enterprise app.

I tried to migrate to beta11, since angular-material required 5.0.2 and it did not want to work with the earlier project deps.

I also tried on beta 10 of the skeleton to change just the angular deps to bump them up, but then webpack starts to fail with strange errors.

**Comment by Ks89** [comment]
> It is very frustrating how they fuck up things from Angular 5.0.0.beta7 to 5.0.2 this is really annoying

Yes I know, but this is a big improvement and now we can also use aot in watch mode.

Today all my personal projects are build with angular 4. During Christmas holidays I'll try to migrate some of them to angular-cli. Also, I have to rewrite one of them with material, so during this winter I'll build a project with some branches to try different configurations.

I can create a project right now, but I think that it isn't useful. What I did with my skeleton is to create a project and test it with different projects. So I want some projects to angular cli before to start to create a skeleton. I want to create a skeleton based on real experiences in an enterprise environment. 

Your suggestion to add those dependencies is very good and I'll do it for sure. 


PS yes you cannot update only thosr because you have to change webpack config a day other stuff. 

Ps2: today I'm using angular-cli for a library on npm and a demo on github... In some weekes I'll use it everywhere

**Comment by ltoshev** [comment]
Ok for now we stick with beta10, and will wait to see what will happen when beta11 is stable.

PS: Can you suggest how to include tether? It seems defined in beta10, but have trouble using it?

**Comment by Ks89** [comment]
Tether is working because bootstrap 4 is using it and its ok.

Do you have any issues about tether?

**Comment by ltoshev** [comment]
Abou Tether: I managed to get it a kind of going.

I have another questions about SCSS:

.do-group-name {
        @extend %global.button;
...
        @include breakpoint(medium) {
            padding-top: 16px;
        }
    }

Why those things fails the build, when they are in a stylesUrl of a component?

Those are SCSS stuff, and they need to try to be compiled?

How is the order of scss compiled? First components, then styles.scss -> which is the root scss file and I have included all refs there in the right order?

I think components scss should go after styles.scss

How is it loading it now?

**Comment by Ks89** [comment]
Honestly I don't rebemeber. I never tried this thing with scss in this skeleton.
I should check, but I need to do some esperiments. Now I have to do other stuff, so I'll try later.

**Comment by Ks89** [comment]
@ltoshev I started a new project called 'angular-cli-skeleton' here: https://github.com/Ks89/angular-cli-skeleton

It's working, however is still young and I need to add and fix many things. I'm working on beta.1.
I suggest to switch, because I'll migrate all my personal and enterprise applications to that one.

**Comment by Ks89** [comment]
Project officially deprecated and replaced by https://github.com/Ks89/angular-cli-skeleton

All issues will be closed

I hope to see all of you to use my new project based on angular-cli (recommended today)

**Comment by Ks89** [comment]
Project officially deprecated and replaced by https://github.com/Ks89/angular-cli-skeleton

All issues will be closed

I hope to see all of you to use my new project based on angular-cli (recommended today)
